# Generated by Django 5.1 on 2024-08-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_List', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_price',
            new_name='amount',
        ),
    ]
